/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic framework code for a JUCE plugin editor.
 
 -This is a guitar (bass and electric) effects plugin with tremolo, two gain stages, and stereo width.
 -Referenced files/sites:
 -++delay.jucer - Tom Erbe
 -stereo width: http://musicdsp.org/showArchiveComment.php?ArchiveID=173
 
 ==============================================================================
 */

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
 */
class PurpleAudioProcessorEditor  : public AudioProcessorEditor,
public Timer,
private Slider::Listener
{
public:
    PurpleAudioProcessorEditor (PurpleAudioProcessor&);
    ~PurpleAudioProcessorEditor();
    
    //==============================================================================
    void timerCallback() override;
    PurpleAudioProcessor* getProcessor() const
    {return static_cast<PurpleAudioProcessor*>(getAudioProcessor());}
    
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged(Slider* slider) override;
    
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    PurpleAudioProcessor& processor;
    
    //sliders
    Slider gainOne;
    Slider gainTwo;
    Slider rate;
    Slider lfoDepth;
    Slider stereoWidth;
    Slider input;
    Slider output;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PurpleAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
